ScreepsOCS/screeps.behaviour-action-pattern

- README.md
- creep.action.claiming.js
- creep.action.guarding.js
- creep.action.harvesting.js
- creep.action.healing.js
- creep.action.invading.js
- creep.action.settling.js
- creep.action.withdrawing.js
- creep.behaviour.claimer.js
- creep.behaviour.healer.js
- creep.behaviour.melee.js
- creep.behaviour.pioneer.js
- creep.behaviour.privateer.js
- creep.behaviour.worker.js
- creep.js
- creep.setup.claimer.js
- creep.setup.healer.js
- creep.setup.melee.js
- creep.setup.pioneer.js
- creep.setup.privateer.js
- creep.setup.ranger.js
- creep.setup.worker.js
- extensions.js
- global.js
- population.js
- spawn.js
Major changes:  
* New creep type *Privateer* for harvesting in neutral rooms
* Extended Flag system
* Fixed some bugs with the healer
> July update

- creep.Action.js
- room.js
build roads:
simple algorithm to determinate best location for paths based on history of movements.
each location has count which is incremented when creep stamp on it (or mine)
after 100 tick the counts below mean are pruned and rest are reduced by mean value
best 2 are chosen to be new location for road.
> build roods

- creep.behaviour.privateer.js
- room.js
Privateers can build roads, log fixes
> Road planner fixes

- room.position.js
find closes point in range from another point
> Closes position to point a from point in range to point b

- extensions.js
- room.position.js
More goodes in RoomPosition extension:
1. find open positions in range(range <= ) and at range (range == )
2. find subset of positions next to given position.
> Find best position for mining container.

- creep.Action.js
* prefer own rooms,
* hight ways
* marked with exploit flag
Fixes issue with running into guarded rooms and stacking on rooms with protection.
> Better path finder across multiple rooms:

- creep.behaviour.hauler.js
- room.js
@mikiones please keep the branch up to date with changes in dev. Simply create a pull request with 
base: containerFlags, head: dev 
to sync changes made in dev down to the branch.
> Merge ok? 

- creep.Action.js
- creep.action.charging.js
- creep.action.harvesting.js
- creep.action.idle.js
- creep.action.picking.js
- creep.action.uncharging.js
- creep.behaviour.hauler.js
- creep.behaviour.miner.js
- creep.behaviour.pioneer.js
- creep.behaviour.upgrader.js
- creep.behaviour.worker.js
- creep.setup.hauler.js
- creep.setup.upgrader.js
- extensions.js
- global.js
- main.js
- parameter.js
- room.js
@ScreepsGamers/members 
This is a larger one, thats why I am using a feature branch. I think it could be merged now. My rooms are already running on it. 
Please have a look at it. Maybe somebody could also do some additional tests. 
Implements 
* #109 source & controller nearby 
* #124 conditional dropmining
> Container classification

- creep.setup.upgrader.js
`!spawn.room.storage ||` missing again..
> Upgrader-NoStorage bugfix

- creep.behaviour.miner.js
- creep.behaviour.upgrader.js
> Fixing action/target registration

- room.js
- tower.js
Sorry I'm new at coding, must be a better way to save the array of whitelisted players in parameters or something.
> Super Basic Whitelist for friends

- room.js
> typo in PLAYER_WHITELIST

- room.js
Added link to build priority list
> Added link to build priority list

- spawn.js
> Spawn loop only in owned rooms

- parameter.js
> Welcome C00k1e_93

- room.js
Within the build priority list, work on the site with the highest percentage of progress.
> Always build on the construction site that's closest to complete.

- creep.js
to reduce unnecessary spawning via springGun
> adjusting threat calculation (tower & heal weight)

- creep.behaviour.worker.js
> picking is better than idle

- task.js
Broken by 223cfed59f0b59229078a5f97aa46495cf317b03
> Fixing task compileBody

- creep.behaviour.privateer.js
- task.js
- task.robbing.js
Sends hauler based robbers to rooms (used when we find rooms with full storage's).
Only triggered via specific robbing flag. 
Privateers can still be used for current functions: Dismantle, support robbing, building and exploiting sources. Will not migrate currently unless we find a good use for privateers.
> Task based robbing

- creep.behaviour.hauler.js
> hauler quick fix

- task.reserve.js
> move queued reserver to medium queue upon low reservation

- creep.behaviour.claimer.js
- creep.behaviour.hauler.js
- creep.behaviour.healer.js
- creep.behaviour.melee.js
- creep.behaviour.pioneer.js
- creep.behaviour.privateer.js
- creep.behaviour.ranger.js
- creep.behaviour.remoteHauler.js
- creep.behaviour.remoteMiner.js
- creep.behaviour.remoteWorker.js
- creep.behaviour.worker.js
- population.js
> clear creep path upon each action assignment

- creep.action.attackController.js
bringing this in line with the standard error messaging and handling
> Creep.handleError

- creep.behaviour.remoteMiner.js
Fixed issue with remoteMiners not handing off properly when replaced.
> Allow remote miners to take over for miners which need to be replaced

- creep.js
- global.js
traces I added looking at the movement cycle bug
> movement traces, default message for trace

- task.mining.js
Easy to use and only in effect with manual intervention.
> Task.mining.storage("flagRoom", "storageRoom");

- creep.action.reallocating.js
> Change/reallocating: Haulers will make space in full terminal for TERMINAL_ENERGY

- creep.Action.js
- creep.js
- strategy.js
Demo implementation: https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/commit/58ca146a026900894eb55732e59060a1a8cf2c5d
Documentation in comments here.
> strategy API

- room.js
> resolves #670 undef check and off-by one direction transform

- room.js
This patch addresses internal issue # 185. Fix from georgeberkley.
> patch to avoid statistics for SKs which causes an error

- creep.behaviour.recycler.js
quick fix for the recycler taking over another action
> recycler bugfix

- room.js
> More sophisticated mapping of terminal to source

- strategy.js
this might help CPU problems in dev
> avoid stringifying dangerous params

- task.reputation.js
I think this is the last must fix for 2017-2
this resolves #710
> player reputation is case insensitive

- creep.action.travelling.js
- creep.behaviour.privateer.js
this is extremely useful when settling a new area (portals etc)
> privateer can travel to room without vision

- room.js
> attempting to fix for all SK rooms

- creep.setup.upgrader.js
> Limit upgraders at Level 8 with separate setup

- README.md
- creep.action.harvesting.js
- main.js
- room.js
- task.js
- task.reputation.js
this is a conflict resolved master, which contains all the RC fixes from 0.6.0
> 0.6.0 Rc fixes merge to dev

- creep.action.upgrading.js
> Workers shouldn't upgrade at RCL8

- creep.behaviour.ranger.js
- population.js
this is a major combat strategy change. Accompanied by internal changes.
> coreHits: ranger only heal when you are losing your life

- creep.setup.hauler.js
- creep.setup.mineralMiner.js
- creep.setup.upgrader.js
i figured out why I was having trouble customizing upgrader counts
> upgrader, miner, hauler maxCount dereference so that they are customizable

- creep.action.fortifying.js
- creep.action.storing.js
- creep.action.upgrading.js
- creep.behaviour.upgrader.js
- creep.setup.hauler.js
- creep.setup.upgrader.js
- creep.setup.worker.js
- room.js
still need to test this, but it's simple tho there are many many cases so have at reviewing this
The purpose of this is to normalize how we address energy storage as a relative number. This hopefully makes our logic more comprehensible and consistent.
"charge" is just the percent of "full" - so 200% full means "i've got too much energy and need to spend it now!"
> storage charge

- room.js
@OverlordQ  please find the issue for this if there was one filed
> avoid undef when updating orders

- creep.js
ranger is the reference for healing
> creeps heal when fleeing

- traveler.js
this adds the OCS room-by-room pathfinding to traveler as a fallback when things go wrong
> attempt to solve routing problems first using transit of adjacent room

- commands.js
- creep.action.avoiding.js
- creep.action.fortifying.js
- creep.action.storing.js
- creep.action.travelling.js
- creep.action.upgrading.js
- creep.behaviour.claimer.js
- creep.behaviour.miner.js
- creep.behaviour.remoteMiner.js
- creep.behaviour.upgrader.js
- creep.js
- creep.setup.hauler.js
- creep.setup.miner.js
- creep.setup.upgrader.js
- creep.setup.worker.js
- extensions.js
- flagDir.js
- global.js
- main.js
- parameter.js
- room.js
- task.mining.js
- task.pioneer.js
- task.reserve.js
- task.robbing.js
Reverts ScreepsOCS/screeps.behaviour-action-pattern#865
> Revert "update powerMining test"

- creep.action.avoiding.js
> only avoid offensive military creeps

- creep.Setup.js
- population.js
I would like to merge this into your branch, but not sure the scope you wanted to keep.
> Local Creeps use predictedRenewal

- room.js
the power and energy check values were reversed
> fixed energy and power check before process

- creep.action.defending.js
basic way to parameterize this
also I think the healing filter was broken
> added defending strategy for basic target selection customization

- creep.action.guarding.js
- creep.behaviour.melee.js
- creep.behaviour.ranger.js
working on a more elegant way to do this, but it works
> guards can sit on border and disengage to chase hostiles in either room

- population.js
Makes our detection more robust, and less prone to errors when we miss a tick for whatever reason.
> Better Creep Birth/Death detection

- task.reputation.js
> when your spawns are gone, don't crash

- visuals.js
quick visuals fix, already applied to rc1
> energy bar can be over 100%

- creep.behaviour.miner.js
- creep.behaviour.mineralMiner.js
- creep.js
This lays the foundation for being able to define all kinds of miners as "Miners" with dynamic source selection (energy/minerals) and location (local/remote).
> Shared logic for all miners, with separate source selection.

- global.js
as per Karls request for auto building
> Change flag colour reservation

- room.js
allows walking on own road and rampart sites
> don't avoid walking on own sites

- room.js
Eventually rooms beyond 99 will be added. I actually believe PTR runs 100+ so observers wouldn't work properly there.
> Fix RegEx check

- util.diamond.iterator.js
this does what it says, try it!
If you would like to add the an open-border (dotted?) strictly diamond shape to this code please do so. I'll be using it for pathfinding so it had to be closed.
> closed borders diamond iterator

- creep.js
- strategy.js
@OverlordQ this one is for you - it's only partially done, but maybe you can help with the innards.
Right now you can do this:
```
> Game.getObjectById('58d2eb8ca45ad69f4dbdf5f2').explain()
< hauler-1250-2: assigned (storing,hauler,)
```
If any of the creep's strategy clients (e.g. Action, Behaviour, Task) implement the explain(creep) function then that method's return value will be appended.
> creep.explain() tries to explain what the creep is doing

- creep.action.bulldozing.js
- creep.behaviour.claimer.js
- creep.behaviour.worker.js
- main.js
Really hope I've done this right.
> Bulldoze Action

- room.js
Three methods were identical to the other methods. Bad merges.
> Remove Duplicate Methods

- flagDir.js
Hate typing out the full comparison check every time
> Easily compare flags

- main.js
- visuals.js
Makes it a little easier to understand what you're looking at and to extend it with virals. I've set a few styles to start off with.
> Visuals Refactor

- creep.behaviour.collapseWorker.js
- main.js
- task.pioneer.js
this is 100% untested, but I'm tired of hearing about this
#888
> the collapse recovery worker its own behaviour: collapseWorker

- creep.action.robbing.js
- util.js
This could be considered a work in progress since it deserves the strategy treatment, but I want to refactor storeCall / targetCall into the base OCS API.
I recommend split diff.
> robbers take valuables first

- creep.action.attackController.js
- creep.action.avoiding.js
- creep.action.building.js
- creep.action.bulldozing.js
- creep.action.charging.js
- creep.action.claiming.js
- creep.action.defending.js
- creep.action.dismantling.js
- creep.action.dropping.js
- creep.action.feeding.js
- creep.action.fortifying.js
- creep.action.fueling.js
- creep.action.guarding.js
- creep.action.harvesting.js
- creep.action.healing.js
- creep.action.idle.js
- creep.action.invading.js
- creep.action.picking.js
- creep.action.reallocating.js
- creep.action.recycling.js
- creep.action.repairing.js
- creep.action.reserving.js
- creep.action.robbing.js
- creep.action.storing.js
- creep.action.travelling.js
- creep.action.uncharging.js
- creep.action.upgrading.js
- creep.action.withdrawing.js
- parameter.js
Creep actions' `onAssignment` has been updated from `fromCharCode` to `fromCodePoint`. Most action emojis are the same, however in attempt to give each action a unique emoji, some are different, (few have multiple).
If one doesn't display for you, let me know the action, your OS, and browser, and I will try and select a new one.
> Action onAssignment Statement

- task.guard.js
> this should allow guards to spawn in the same room they are wanted in.

- extensions.js
Didn't end up needing this, but it still might be useful.
> Get all positions in radius

- creep.setup.upgrader.js
@TafThorne here's the issue you triaged
> don't spawn an upgrader when rebuilding a level 8 room

- task.mining.js
This paves the way for a more customizable task.mining so that we can implement SKMining internally using virals.
> Further parameterize task.mining using strategies

- creep.action.fortifying.js
Will fortify with 0.6 charge instead of max charge.
> Fortify energy requirement reduction

- task.reserve.js
This needs testing to verify, resolves  #1147
> Fix reservers spawning when we lack visibility

- spawn.js
> Disable spawning of non-critical roles

- flagDir.js
- main.js
- room.js
without try/catch, thrown exception halt script execution, collapsing
colonies
> wrap main in try/catch

- commands.js
- task.js
Currently there was no way to do this cleanly. This still isn't clean but it's better than nothing. Duplicate code can be cleaned come refactors.
> Force spawn a Task.

- creep.setup.upgrader.js
- visuals.js
Adds an indicator to global visualization for empire-wide spawn pressure.
> Visualize Empire Spawn Pressure

- creep.action.healing.js
adds strategy capability to healing so that users / internal can viral the target selection
> healing strategy

- main.js
Does the same thing without recursively calling itself.
> Merge Objects on Inject

- room.js
This resolves https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/issues/1339
> hotfix/cachedFeeding - make sure memory cache of extensions and spawns is up to date

- room.orders.js
[PTR Changelog](http://support.screeps.com/hc/en-us/community/posts/115001949525-PTR-Changelog-2017-05-04)
Despite being a PTR feature, this will work fine if it gets merged.
> Implement Terminal Cooldown

- creep.action.avoiding.js
Also slight refactor to clean up readability.
> fix/viralAvoidance - allow viral override of dangerRange

- flagDir.js
- room.js
This will save some CPU when searching for local flags.
Also did a little reformatting to clean the syntax.
> Cache Room Flags

- room.js
- traveler.js
move creepMatrix out to an accessor function so the base matrix can be parameterized, fix getAvoidMatrix to check whether the position is walkable before setting costs, this avoids creeps trying to walk into walls.
> [0.7.0] - fix/avoidSKMatrix

- README.md
- creep.action.robbing.js
- creep.setup.hauler.js
- room.construction.js
- room.js
- room.spawn.js
- traveler.js
- visuals.js
Merge master back into dev after release, I based this off dev, merged master into it and then resolved conflicts.
> 0.7.0 Release -> dev

- creep.action.mining.js
- task.mining.js
remove our use of FIND_DROPPED_ENERGY to avoid spamming console with warning messages.
> hotfix/findDroppedEnergy - FIND_DROPPED_ENERGY is deprecated
