ScreepsOCS/screeps.behaviour-action-pattern

creep.behaviour.worker.js
_.concat is not supported  in Lodash 3.10, which screeps uses. 
(PTR server is an exception on this)
=> _.concat is not supported in Lodash 3.10

creep.action.reserving.js, creep.behaviour.claimer.js, creep.js, creep.setup.claimer.js, global.js
Allow claimers to reserve rooms without claiming them using a grey flag. Lower priority than the claiming action.
=> Add reserve action for claimers

creep.action.uncharging.js, population.js
send only those creeps what have chance to get energy from container. i.e.  container.stored - sum(conteiner.targetof.empty_space_in_creep) > 0
=> better uncharged action creep distribution 

creep.behaviour.hauler.js, parameter.js, room.js
Haulers get confused when central and mining link are full, trying to pick up dropped energy instead of uncharging the central link to solve the jam.
And small changes.
=> Prioritize link uncharging

creep.action.upgrading.js, creep.setup.hauler.js
For quite a while, worker weren't allowed to upgrade the controller as soon as there is a storage (due to a bug). 
In the meanwhile the upgrader is much more variable in its size, and I like that. 
Now (as the bug is fixed) workers (and privateers!) will support with upgrading (as soon as the storage level reaches MAX_STORAGE_ENERGY). That will block them to do other jobs. 
I believe the upgrader is able to manage the energy level of the storage on its own (will become larger/smaller), and should do it alone. 
What do you think?
=> Dont allow worker/privateer upgrading with storage

creep.setup.claimer.js
Since it only takes 1 CLAIM component to claim an unclaimed controller, create a small, affordable claimer setup to allow for claiming emptry rooms at lvl 3.
=> Create a small claimer at lvl 3 to allow for claiming empty rooms.

creep.Setup.js, creep.setup.melee.js, creep.setup.ranger.js, global.js
this fixes the issue where all flag-based spawns come in waves
this was non-trivial... so it also adds Creep.Setup.debugType. With DEBUG enabled, set Creep.Setup.debugType = Creep.setup.ranger.type in order to see the valid setup decisions printed.
=> fix maxCount based on flags

creep.Action.js, creep.action.claiming.js, creep.action.reserving.js, creep.action.upgrading.js, creep.js, extensions.js, main.js
This change consolidates most action errors into `Creep.prototype.onError(tryAction, tryTarget, errorCode)`
Additionally the event Creep.actionError is raised and event listeners should signal that the error was recovered and should not be logged by calling `delete creep.resolvingError`
Example implementation: https://github.com/karlthepagan/screeps.behaviour-action-pattern/commit/60aff5612a6cf88c23327023838552625d69d53d
=> Creep.onError and Creep.actionError event

creep.action.feeding.js
"spawn".targetOf can be recycling action. When creeps are recycling, haulers and workers won't feed energy to the spawn.
=> Fix for feeding.

commands.js
When the code gets stuck it is helpful to clear the command queues.  These examples will clear each level of queue in a room. 
This patch was mentioned in issue #525.
=> Add Clear Spawn Queue Examples To commands.js

spawn.js
If a room gets wiped, and a large cost worker is left in the queue, it gets stuck.  No point waiting for enough resources when they aren’t coming!
=> Fix when no creeps remain and large cost creep is in queue.

population.js
The error only really showed up once, until the creeps spawned by the missing spawn despawned, this corrects that.
=> If a spawn is destroyed, don’t try to probe it.

strategy.js
oops. found this while testing `change/pickingStrategy`
basically if you define a handler which returns a falsey value (rather than a function) it will return undefined and scream an error message
this isn't fatal, but it's far from ideal
=> don't return error message when result of strategy handler is falsey

creep.behaviour.remoteMiner.js, creep.js, parameter.js
This small addition allows remote haulers to build their own roads and containers. It is implemented along with Creep.repairNearby and only searches for construction sites within a range of 1 to save cpu time. Depending on strategies this can make the remote worker superfluous. Experimenting can be done with setting the REMOTE_WORKER_MULTIPLIER in the parameter file to 0 to save on spawn time.
=> added build nearby for remote haulers with range 1 to Creep.repairNearby

task.mining.js
Allows remote mining rooms to deliver mined energy to another room.
Best when two owned rooms both border a single remote mining room.
_____________
Has been extensively tested via canary and performed extremely well. 👍
=> Task.mining.storage("flagRoom", "storageRoom");

strategy.js
for example in this error message
```
error no strategy handler for args {"agent":"remoteHauler-betaOldMine-2","key":[["uncharging"],"remoteHauler","mining"],"method":"withdrawAmount","args":...,"stack":"Error\n    at prototype.getStrategyHandler (strategy:24:106)\n    at creep.action.uncharging:67:42\n    at Action.action.isValidTarget (creep.action.uncharging:9:12)\n    at Action.validateActionTarget (creep.Action:92:23)\n    at validateAssignment (population:233:39)\n    at /opt/engine/node_modules/lodash/index.js:3073:15\n    at baseForOwn (/opt/engine/node_modules/lodash/index.js:2046:14)\n    at /opt/engine/node_modules/lodash/index.js:3043:18\n    at Function. (/opt/engine/node_modules/lodash/index.js:3346:13)\n    at Object.mod.analyze (population:244:7)"}
```
The `key` in the …
=> strategy handler array arg from getStrategyHandler was producing a nested array

strategy.js
when strategy handlers accidentally return undef the cause of the complaint is not clear
this should make that better and also adds the strategyName to make this easier to triage
=> easier to understand undefined handler error, strategyName trace

creep.action.harvesting.js
More of an issue on new rooms, looping niavely through list of sources can occassionally send creeps across room when a valid source is right next to them
=> Pick harvest source based on distance first

task.pioneer.js
pioneers are queued for rooms that can't spawn them
```
Queued creep too big for room: {"parts":["work","work","carry","carry","move","move"],"name":"pioneer-pio3","behaviour":"pioneer","destiny":{"task":"pioneer","targetName":"pio3","flagName":"pio3","room":"E72S7"},"queueRoom":"E73S9"}
```
=> avoid pioneer queue error

creep.action.picking.js
I've noticed things picking up dropped energy waste ***a lot*** of time making back and forth trips to pick up a partial load of dropped energy/minerals. Then, instead of grabbing from the container to fill up and make room for more to be stored, they wander off, leaving the miners to have to drop more energy on the ground.
=> Fill up worker from containers when picking

creep.behaviour.privateer.js
Once again, named the branch wrong, it's the privateer that actually goes home and functions as a worker if they can’t find a room.  Currently they go to the home border when there isn't a "nextRoom" to exploit and they cycle on the border.
=> Privateer goes home

creep.behaviour.upgrader.js
As well as forgetting previous bad spot selection and upgrading as soon as they are in range.  One possible change from old code is the potential range to a source, this checks to ideally choose a spot that is not adjacent to a source if possible.
We could add withdrawing from storage and storage to spot selection as well if we want to.
=> Fix upgrader determinatedSpot selection

creep.behaviour.miner.js, creep.behaviour.remoteHauler.js, creep.behaviour.remoteMiner.js
Quick fix to prevent border cycling.  @whardeman can you try this out to see if it resolves your issues.  Any larger implementation to your issues would not be appropriate for a merge into RC so this will have to do for now.
=> Stop remote miners and haulers from border cycling causing a mess.

creep.action.building.js, room.js
If a creep selects a build site, but paths through an external room to get there it loses its action because that room does not have any construction sites. If we want to prevent the action from being added when there are no construction sites, perhaps the check for constructionSites should be in the isAddableAction instead?
=> Fix build action when transiting through room

creep.action.harvesting.js
Just add a check to validTarget to make sure the source still has enough spaces to harvest.  Prevents heavy CPU usage when trying to path to an unreachable source.
=> Stop trying to harvest if source has no free spaces

task.pioneer.js
I had two rooms die from the handleRoomDied creep.
The simplest fix is to make that this backup creep is only a 200 energy creep.
=> room died creep is too big

extensions.js
The full range represents when energy between min and max.
use cases:
* when you are over max energy storage: room.storage.charge > 1
* when you are under minimum energy storage: room.storage.charge < 0
Numerical computing - this is biased around 100% full, the difference between current and max is the most important comparison in many existing methods.
If the room minimum === maximum then the response is either `Infinity` or `-Infinity`.
=> storage charge property, returns percent of the "full" range

creep.Action.js
if assignment changes from one flag/spawn to another
feels like a possible bug waiting to bite us
=> call Population.registerAction more often

parameter.js, task.pioneer.js
i found this extremely useful, there's better detection for the neutral room error case and `PIONEER_UNOWNED: true` enables neutral pioneering
=> pioneers learned to build up neutral spaces

creep.js, main.js, parameter.js
Gives users the option to overfill their bucket in an attempt to prevent thrashing when the CPU bucket falls below the critical level.
=> Overfill CPU Bucket when below critical threshold

creep.action.feeding.js
This comes with the possibility that there will be some unforseen base layout that causes creeps to select a target that is unreasonably far away.  If you have one of these issues, please report it with details.
=> Change target selection from ByPath to ByRange

creep.behaviour.remoteHauler.js
Previously when remoteHaulers found a potentially chargable target closer than storage, they would potentially ignore the storage.
=> RemoteHaulers use storage in more cases

room.js
Asking for Room.prototype.exits(number) will list room positions that represent each contiguous exit.
Usage:
Find one position representing all the separate portal structures in a room.
> `Game.rooms.E75S5.exits(0)`
< `[{"x":36,"y":19}]`
Find the single large top exit
> `Game.rooms.E75S5.exits(FIND_EXIT_TOP))`
< `[{"x":5,"y":0}]`
Find the single small right exit
> `Game.rooms.E75S5.exits(FIND_EXIT_RIGHT))`
< `[{"x":49,"y":35}]`
Find the three small bottom exits
> `JSON.stringify(Game.rooms.E75S5.exits(FIND_EXIT_BOTTOM))`
< `[{"x":7,"y":49},{"x":20,"y":49},{"x":32,"y":49}]`
Find the two small left exits
> `Game.rooms.E75S5.exits(FIND_EXIT_LEFT)`
< `[{"x":0,"y":3},{"x":0,"y":24}]`
Find all the regular exits
> `Game.rooms.E75S5.exits(FIND_EXIT)`
< …
=> fast enumeration of all exits

creep.setup.hauler.js, creep.setup.miner.js
RCL8 rooms are fragile because these are set too high.  If a room gets into 'collapsed' and only has the emergency worker to fill extensions, and then both miners die, no haulers can spawn.  With remote creeps still spawning the tiny worker has no real chance of getting energy capacity back up to the level that a hauler or miner could spawn.
Miner was set to 30% full, which is 3870 energy at RCL8
Hauler at 40% is 5160 which is also excessive.
This change sets the limit for miners to 1290 and haulers to 2580.
=> haulers and miners are vital spawns, and should be easy to spawn.

creep.behaviour.upgrader.js
Take into account an upgrader's speed when calculating predicted renewal.
=> Upgraders don't move a 1/tick

task.reserve.js
Heavier reservers are more efficient, for CPU & Energy.
eg. assume 100 ticks travel, 400 ticks reserve
small: 2CLAIM,2MOVE
large: 4CLAIM,4MOVE
2xsmall = 200 ticks travel 800 ticks reserve = 1600 reserve (-800 ticks decay) ~ 800 reserve
1xlarge = 100 ticks travel 400 ticks reserve = 1600 reserve (-400 ticks decay) ~ 1200 reserve
this reduces the threshold to 1000, so for a nearby room the heaviest reserver would give us
9CLAIM, 9MOVE, 50 ticks travel 450 ticks reserve = 4050 - 450(decay) = 3600 building it up to ~ 4600.
=> Increase desired weight of reservers

creep.action.feeding.js, creep.action.withdrawing.js, creep.behaviour.hauler.js
This is very similar to your implementation @logxen but I wanted to clean it up and make room for a standard impl that uses our APIs.
=> storage debounce improved - hold withdrawing / storing until an output action target is available

creep.js
I think upgraders should focus on upgrading, this becomes especially important at RCL8 when you want to spend a majority of your ticks upgrading.
This also removes the drive by repair from miners as they have their own means of repairing.
=> Upgraders should not repair, miners have their own checks.

parameter.js, task.mining.js
REMOTE_HAULER_ALLOW_OVER_CAPACITY allows "rounding up" the total capacity
this is VERY shocking to the cpu... you may wish to check out the histogram of your haulers:
`JSON.stringify(_.chain(Game.creeps).filter(i=>i.data.creepType==='remoteHauler').groupBy('data.weight').mapValues(i=>i.length))`
and then recycle the small ones
`_.chain(Game.creeps).filter(i=>i.data.creepType==='remoteHauler').filter(i=>i.data.weight < 1400).map(i=>i.data.creepType='recycler')`
=> remote hauler min weight is more aggressive for the 2nd+ haulers

creep.action.idle.js, creep.action.travelling.js, creep.behaviour.privateer.js, flagDir.js, main.js, population.js, task.defense.js
this attempts to fix the SK circular reference problem
my current hypothesis is that circular references are more likely to occur in SK rooms and this is possible outside that scenario (defenders or privateers traveling to rooms without vision)
the core mechanic is that all creeps use the "special flag" to denote the old self-targeting conditions (idle and travel)
=> creeps may not self target

creep.action.fueling.js
At some point we should update fueling so that they fill towers based on their proximity to hostiles, but this stops them from walking across your room to fill 1 tower and making the invasion even worse.
=> haulers should fill the closest towers first.

creep.setup.upgrader.js
Lowered the threshold for spawn because filling all of the extensions at RCL8 can take quite a long time, and really isn't necessary.
=> RCL8 Upgraders spawn in time to replace and at the right size.

population.js, task.mining.js
Guess what... this one will throw an exception. BECAUSE we want to halt execution before the engine can mess us up.
Not sure what I should do to repair these circulars until I see one. I might be able to delete the keys after we gather a few samples.
This is disabled by default. In order to enable it you MUST add the following code to your viral.mainInjection.js
```
mod.execute = function(){
Population.findCircular();
};
```
=> attempt to check for circular references before the backend find them

creep.Setup.js, creep.setup.hauler.js, creep.setup.mineralMiner.js, creep.setup.privateer.js, creep.setup.upgrader.js, creep.setup.worker.js
This resolves some major inconsistencies with creep setup customization.
Hopefully this will help us realize the features needed for Task-based creep body definitions, or perhaps help us realize the ways we can extend and customize creep body definitions as we transition away from the Setup queue.
=> creep.Setup property dereferencing is more consistent

creep.setup.hauler.js
An RCL8 room with an emergency worker struggles to get up to 2600 energy, but if you can spawn one with ~ 1300 it will get the room back into good shape very quickly
=> Save collapsed RCL8 Rooms

main.js
This change is mainly for parameters that are objects. It will allow you to only overwrite specific keys, so you don't have to copy them all in your virals.
=> Only overwrite keys in the object, not the entire object

creep.action.charging.js
Also converted to use defined constants rather than values.
This should also be an issue in https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/pull/960 and may need to be cherrypicked.
=> isValidTarget was broken for charging links

task.reserve.js
This addresses @TafThorne's problem with reservers spawninig before privateers.
supercedes #621.
=> privateer reserves will always use the low priority queue

global.js, main.js
until the code gets reloaded.  This ensures that it gets properly rebuilt.
Needs to be investigated whether this is also an issue in https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/pull/960
Yes, this would appear to also be an issue in the RC, if this change is approved, the change to add global.install() should be added, but not the patch for fixing an error with the profiling loading.
=> delete Memory.modules would not actually rebuild modules

creep.Action.js, creep.action.picking.js, creep.behaviour.hauler.js, creep.behaviour.remoteHauler.js, strategy.js
Defines the default strategy for picking to only pick energy, currently this strategy is only overridden for haulers and remoteHaulers to allow them to pick resources as well as energy.
=> Implement picking strategy for haulers and remoteHaulers

creep.behaviour.miner.js
didn't notice this until 'use strict' was enabled on a compressed build, not sure how it ever worked.
=> fix undefined source error

creep.Action.js
this allows more than one argument in the getStrategy convenience method
=> fix action.getStrategy varargs

creep.action.withdrawing.js
This change should not be merged until #1249 is resolved as it will drain all terminals down to TERMINAL_STORAGE and put the energy in storage and start a competition between withdraw and reallocating.  However, it does set what I consider to be the correct priority for withdrawing from terminals.
=> withdrawingTargets - use terminal as valid withdraw when charge > 1 and don't debounce terminal

main.js
Set values in Memory.parameters which will override values in parameter.js.  Ideally, Memory.parameters should be deleted whenever new code is pushed, but currently we can't detect the difference between a code push and an instance switch.
=> infectiousMemory - Change parameters in memory without reloading all code

creep.Action.js
This only really comes up with the dropping action, since it uses a reachedRange of 0, and we can't change that on a per-instance basis currently.  This prevents Creep.action from trying to travel to range 0 when the target is blocked and the creep is already adjacent.
=> actionLastSteps - don't try to travel to range 0 if it's blocked

room.lab.js
This resolves a bug I found with manually creating a burst mode: #1314
=> don't cancel child lab order if master id doesn't match

creep.action.dropping.js
might need some help on this one. I've got a quick test that halts broken haulers and sets them in the right direction but I haven't tested the outcome or the normal operation of this fix
this prevents creeps with the dropping action from being assigned to any old flag... still not sure how they get assigned to these flags
=> test for valid flag on dropping assignment

creep.Setup.js
This was fixed for tasks, but not for spawns that use setup.  Prevents creeps from taking names of creeps that have died in the same tick.
=> hotfix/populationUndefined - avoid creeps without population entry
